### ISSUE TITLE
changing scripts in json view doesn't update code

### ISSUE THREAD

**Issue by bruh-9000** [moddio/moddio2#643]
Changing scripts while in the json view of a script does not update the code shown on screen

**Comment by minotalen** [comment]
should be fixed in 2.0.10, please test

**Comment by bruh-9000** [comment]
it isn't fixed right now, but it looks like it had its appearance changed.
